packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.8.0
  prettier: ^3.3.2
  typescript: ^5.5.4

  tailwindcss: "^3.4.7"
  "tailwindcss-animate": "^1.0.7"
  postcss: "^8.4.40"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
